module.exports = [
  "APPLE","RIVER","ROBOT","CASTLE","TIGER","PLANET","BRIDGE","GUITAR","DESERT","ROCKET",
  "SHADOW","CROWN","ISLAND","MIRROR","ENGINE","FOREST","ARROW","DRAGON","GLASS","ANCHOR",
  "COMPASS","THUNDER","VOLCANO","GARDEN","PIRATE","WIZARD","CANDLE","CIRCUS","DIAMOND","EAGLE",
  "FALCON","GHOST","HAMMER","ICEBERG","JUNGLE","KETTLE","LANTERN","MAGNET","NEEDLE","OASIS",
  "PENGUIN","QUARRY","RAINBOW","SATELLITE","TORNADO","UMBRELLA","VAMPIRE","WHALE","XYLOPHONE","YACHT",
  "ZEBRA","ARMOR","BATTERY","CACTUS","DOLPHIN","EMPIRE","FEATHER","GALAXY","HARBOR","IGLOO",
  "JACKET","KNIGHT","LABYRINTH","MOUNTAIN","NEBULA","ORCHARD","PYRAMID","QUEEN","REACTOR","SPHINX",
  "TRIDENT","UNICORN","VOLTAGE","WATERFALL","XRAY","YETI","ZEPPELIN","ASTEROID","BEACON","CANYON",
  "DUNGEON","ECLIPSE","FORTRESS","GLACIER","HORIZON","IVORY","JADE","KINGDOM","LIGHTNING","MASK",
  "NEST","OPERA","PALACE","QUICKSAND","RUBY","SADDLE","TEMPLE","UNDERGROUND","VELVET","WHISTLE",
  "XENON","YOLK","ZODIAC","ANCHOR2","BAMBOO","CATAPULT","DIAMOND2","EMERALD","FLUTE","GONDOLA",
  "HELMET","INK","JUKEBOX","KAYAK","LOCOMOTIVE","MASQUERADE","NAVY","OBELISK","PARACHUTE","QUILL",
  "RADAR","SUBMARINE","TELESCOPE","URN","VULTURE","WINDMILL","XYLO","YARN","ZIGZAG","AMULET",
  "BLIZZARD","CHISEL","DYNAMITE","EMBER","FOSSIL","GEYSER","HATCHET","INVENTOR","JESTER","KEYSTONE",
  "LOOM","MAMMOTH","NOMAD","OUTPOST","PADLOCK","QUARTZ","RAFT","SICKLE","TUNDRA","UTOPIA",
  "VORTEX","WARSHIP","XYLOGRAPH","YEOMAN","ZEALOT","ABBEY","BLACKSMITH","CATACOMB","DRAWBRIDGE","ENCHANT"
].filter(w => !w.endsWith("2"));
